package com.plasticsmoke.beryl.app

import android.content.res.AssetManager
import android.util.Log
import com.plasticsmoke.beryl.astro.ActionHooks
import com.plasticsmoke.beryl.astro.AlarmState
import com.plasticsmoke.beryl.astro.StopwatchState
import com.plasticsmoke.beryl.astro.WatchTimeState
import com.plasticsmoke.beryl.astro.registerActionFunctions
import com.plasticsmoke.beryl.astro.registerAlarmFunctions
import com.plasticsmoke.beryl.astro.registerStopwatchFunctions
import com.plasticsmoke.beryl.astro.registerTerraFunctions
import com.plasticsmoke.beryl.astro.registerTimeFunctions
import com.plasticsmoke.beryl.astro.registerWatchFunctions
import com.plasticsmoke.beryl.expr.Environment
import com.plasticsmoke.beryl.expr.createDefaultEnvironment
import com.plasticsmoke.beryl.render.LoadedImage
import com.plasticsmoke.beryl.render.applyInits
import com.plasticsmoke.beryl.watch.ModeFilter
import com.plasticsmoke.beryl.watch.Watch
import com.plasticsmoke.beryl.watch.parseWatchXml
import org.json.JSONObject
import java.util.TimeZone
import java.util.concurrent.Executors

/** One face's manifest entry (from faces.json, generated by tools/gen_face_manifest.py). */
class FaceInfo(
    val name: String,
    val display: String,
    val xml: String,
    val thumb: String,
    val images: List<ImageSpec>,
    /** iOS-only leaves (alarm/stopwatch/GPS) stubbed to the same constants the render tests use. */
    val stubs: Map<String, Double>,
    /** Env variables set before applyInits (e.g. Miami's selected body = Saturn). */
    val vars: Map<String, Double>,
) {
    class ImageSpec(val key: String, val file: String, val scale: Double)
}

object FaceCatalog {
    fun load(assets: AssetManager): List<FaceInfo> {
        val root = JSONObject(FaceLoader.text(assets, "faces.json"))
        val arr = root.getJSONArray("faces")
        return List(arr.length()) { i ->
            val f = arr.getJSONObject(i)
            val imgs = f.getJSONArray("images")
            FaceInfo(
                name = f.getString("name"),
                display = f.getString("display"),
                xml = f.getString("xml"),
                thumb = f.getString("thumb"),
                images = List(imgs.length()) { j ->
                    val im = imgs.getJSONObject(j)
                    FaceInfo.ImageSpec(im.getString("key"), im.getString("file"), im.getDouble("scale"))
                },
                stubs = f.getJSONObject("stubs").let { o ->
                    o.keys().asSequence().associateWith { k -> o.getDouble(k) }
                },
                vars = f.getJSONObject("vars").let { o ->
                    o.keys().asSequence().associateWith { k -> o.getDouble(k) }
                },
            )
        }
    }
}

/**
 * The env's display-time source, driven per frame by the renderer: [startFrame] pins the frame
 * instant, and the [beat] callback quantizes what the expressions see to each part's `update`
 * cadence (iOS beat model — a seconds hand with update='.25' ticks 4× a second, Tombstone's
 * balance wheel at update≈8ms rocks smoothly, both from the same continuous expressions).
 */
class FrameClock : com.plasticsmoke.beryl.astro.TimeSource {
    @Volatile private var frameMs: Long = System.currentTimeMillis()
    @Volatile private var sampleMs: Long = System.currentTimeMillis()
    private val tz = TimeZone.getDefault()

    override fun nowMillis(): Long = sampleMs

    fun startFrame(nowMs: Long) {
        frameMs = nowMs
        sampleMs = nowMs / 1000 * 1000
    }

    /** Epoch of the beat containing [frameMs], aligned to LOCAL time — a sub-day-update part
     *  (seconds/minutes/hours) samples on its interval grid so values TICK like iOS parts
     *  that only re-evaluate when their update fires. The tz offset is a multiple of 15 min,
     *  so sub-second and second/minute beats are unaffected.
     *
     *  DAY-scale-and-longer intervals are NOT quantized: iOS never quantizes the sampled
     *  time by the part interval (it evaluates at the current beat-latched time whenever an
     *  update fires), and their leaves are STEP functions that roll on their own calendar —
     *  in their own TIMEZONE. Quantizing to the device-local day broke both Geneva's year
     *  window (365.25-day tiles land mid-year → last year for up to ~18 h of January) and
     *  Terra's top-city date (device-midnight frozen sample reads YESTERDAY all day for any
     *  city in a timezone behind the device's). */
    private fun epochOf(im: Long): Long {
        if (im >= 86400_000) return frameMs
        val off = tz.getOffset(frameMs)
        return (frameMs + off) / im * im - off
    }

    val beat = object : com.plasticsmoke.beryl.render.BeatClock {
        override fun beat(intervalSeconds: Double): Double {
            val im = (intervalSeconds * 1000).toLong().coerceAtLeast(8)
            val epoch = epochOf(im)
            sampleMs = epoch
            return (frameMs - epoch).toDouble() / im
        }

        override fun frameTimeMs(): Long = frameMs
    }
}

/** A face fully loaded for rendering: parsed watch + env per mode, plus its decoded images. */
class LoadedFace(
    val states: List<ModeState>,
    val images: Map<String, LoadedImage>,
    /** The face's displayed-time state (iOS: one mainTime per watch) — shared by all modes. */
    val time: com.plasticsmoke.beryl.astro.WatchTimeState,
    /** Stage-3 subsystems (Olympia chronograph, Istanbul/Thebes alarm) — shared by all modes. */
    val stopwatch: StopwatchState,
    val alarm: AlarmState,
) {
    /** [cache] holds the baked static-run sprites for this watch+env (discarded with the state). */
    class ModeState(val watch: Watch, val env: Environment, val clock: FrameClock) {
        val cache = com.plasticsmoke.beryl.render.StaticCache()

        /** Variables the baked static content reads — actions that touch none of these (and
         *  call only pure leaves) skip the 30-80 ms static rebake that judders sweeps. */
        val staticVarRefs: Set<String> by lazy { com.plasticsmoke.beryl.render.staticVarRefs(watch) }

        /** Non-math function leaves the baked content reads — empty (every shipped face)
         *  means even a time/stem/alarm act can't change what the statics draw. */
        val staticVolatileFuncs: Set<String> by lazy {
            com.plasticsmoke.beryl.render.staticVolatileFuncRefs(watch)
        }

        /** Buttons baked inside `<static>` blocks: pressing these still needs an invalidate. */
        val staticBakedButtons: Set<com.plasticsmoke.beryl.watch.ButtonPart> by lazy {
            com.plasticsmoke.beryl.render.buttonsBakedInStatics(watch)
        }

        /** Fastest effective part-update interval (ms), for the app's render scheduling.
         *  Between epochs nothing moves on its own; in-flight sweeps (the escapement's click)
         *  are carried by the render loop's isAnimating self-repost. */
        val minUpdateMs: Long by lazy {
            val minS = watch.parts.minOfOrNull { part ->
                com.plasticsmoke.beryl.render.updateIntervalOf(part, env, watch.beatsPerSecond)
            } ?: 1.0
            (minS * 1000).toLong().coerceIn(16, 1000)
        }
    }
}

/**
 * Parse + build the environment for one mode of a face: manifest vars (overlaid by any
 * persisted values — e.g. Miami's saved planet) before applyInits, stubs after
 * registerWatchFunctions (so a stub always wins over a real registration), Terra's extra
 * world-clock registration (the only face with one — same as its render test).
 */
fun buildModeState(
    face: FaceInfo,
    xml: String,
    mode: ModeFilter,
    location: LocationStore,
    varStore: FaceVarStore? = null,
    time: com.plasticsmoke.beryl.astro.WatchTimeState? = null,
    stopwatch: StopwatchState? = null,
    alarm: AlarmState? = null,
): LoadedFace.ModeState {
    val watch = parseWatchXml(xml, mode)
    val env = createDefaultEnvironment()
    val clock = FrameClock()
    for ((k, v) in face.vars) env.variables[k] = v
    varStore?.load(face.name)?.forEach { (k, v) -> if (!k.startsWith("__")) env.variables[k] = v }
    val tzOffsetSec = TimeZone.getDefault().getOffset(System.currentTimeMillis()) / 1000.0
    registerWatchFunctions(env, tzOffsetSec, location.latRad, location.lonRad, clock)
    if (face.name == "Terra") registerTerraFunctions(env, clock)
    if (varStore != null) {
        registerActionFunctions(
            env,
            ActionHooks(saveBody = { v -> varStore.put(face.name, "body", v) }),
        )
    }
    for ((k, v) in face.stubs) env.functions[k] = { v }
    // Real GPS leaves (iOS ECLocationManager via ECVirtualMachineOps:3786-3872), overriding the
    // AtlantisIV manifest stubs that exist for the render tests: live altitude/accuracy from
    // LocationStore; goodAccuracy = fix under ECDefaultHorizontalError (101 m) — Uraniborg's
    // bad-accuracy sidereal fallback now engages without one; locationIndicatorAngle π/2 good /
    // π uncertain / π/4 manual (our persisted-position state maps to ECLocManual); SIUnits by
    // locale (iOS defaults the user pref by region — US/LR/MM imperial).
    env.functions["altitude"] = { location.altitudeM }
    env.functions["horizontalPositionError"] =
        { if (location.accuracyM.isNaN()) 101.0 else location.accuracyM }
    env.functions["goodAccuracy"] = { if (location.goodAccuracy) 1.0 else 0.0 }
    env.functions["locationIndicatorAngle"] = {
        when {
            location.accuracyM.isNaN() -> Math.PI / 4   // persisted/manual position (ECLocManual)
            location.goodAccuracy -> Math.PI / 2        // live good fix
            else -> Math.PI                             // live poor fix
        }
    }
    env.functions["SIUnits"] =
        { if (java.util.Locale.getDefault().country in listOf("US", "LR", "MM")) 0.0 else 1.0 }
    // The engine env runs on a FIXED tz offset (no Olson data) and stubs DSTNumber to 0; the
    // app has real tz rules. iOS reads the DST flag from the watch's time env
    // (ECVirtualMachineOps DSTNumber) — evaluate it at the DISPLAYED instant, so Atlantis/
    // Geneva's DST indicator hands are right and follow time travel across DST boundaries.
    val dstTz = TimeZone.getDefault()
    env.functions["DSTNumber"] =
        { if (dstTz.inDaylightTime(java.util.Date(clock.nowMillis()))) 1.0 else 0.0 }
    // The real time-base/stopwatch/alarm leaves must win over both the static stubs and any
    // face stub (the manifest stubs Olympia/Istanbul/Thebes' stage-3 leaves for render tests).
    if (time != null) registerTimeFunctions(env, time)
    // Terra's advanceDayN/MonthN step the shared time in the SLOT city's calendar — they must
    // override the device-zone advances registerTimeFunctions just installed.
    if (face.name == "Terra" && time != null) {
        com.plasticsmoke.beryl.astro.registerTerraTimeFunctions(env, time)
    }
    if (stopwatch != null) registerStopwatchFunctions(env, stopwatch)
    if (alarm != null) registerAlarmFunctions(env, alarm, TimeZone.getDefault().toZoneId())
    applyInits(watch, env)
    // Persisted vars overlay AGAIN after inits: iOS reads persisted state INSIDE the init
    // (Terra: `topRingSlot=fetchPersistentValue(0)`), but our staged XML patches such inits
    // to constants — without the re-overlay the init clobbers the saved value on every
    // rebuild (Terra's top city snapped back to LA). The pre-init overlay stays: inits also
    // DERIVE from persisted vars (Miami computes bodySlot from the persisted body).
    varStore?.load(face.name)?.forEach { (k, v) -> if (!k.startsWith("__")) env.variables[k] = v }
    return LoadedFace.ModeState(watch, env, clock)
}

/**
 * Loads faces on a single background thread and keeps the [MAX_LOADED] most recently used
 * resident (a loaded face holds several decoded 4x bitmaps — all 25 at once would blow the heap).
 * Callbacks fire on the loader thread; callers post to their own thread.
 */
class FaceRepository(
    private val assets: AssetManager,
    private val location: LocationStore,
    private val varStore: FaceVarStore? = null,
) {
    private val executor = Executors.newSingleThreadExecutor { r -> Thread(r, "face-loader") }
    private val cache = object : LinkedHashMap<String, LoadedFace>(8, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, LoadedFace>) =
            size > MAX_LOADED
    }

    /** Per face+mode last-drawn hand angles, kept for the app session (survives LRU eviction). */
    private val animStores = HashMap<String, com.plasticsmoke.beryl.render.AngleAnimStore>()

    /** Session-resident per-face subsystem states (time base, chronograph, alarm) — tiny
     *  objects, shared with any [LoadedFace] built later, surviving its LRU eviction. iOS
     *  keeps every watch resident with its ECAlarmTime armed all session; this is the
     *  Android analog, and what the app's background-alarm scanner iterates. */
    class FaceStates(val time: WatchTimeState, val stopwatch: StopwatchState, val alarm: AlarmState)

    private val faceStates = HashMap<String, FaceStates>()

    @Synchronized
    fun states(faceName: String): FaceStates = faceStates.getOrPut(faceName) {
        val time = restoreTimeState(faceName)
        FaceStates(time, restoreStopwatchState(faceName), restoreAlarmState(faceName, time))
    }

    @Synchronized
    fun cached(name: String): LoadedFace? = cache[name]

    /** Drop all loaded faces (e.g. the observer position changed — envs bake lat/lon in). */
    @Synchronized
    fun clear() = cache.clear()

    /** Persist action-changed env variables so a face's XML state machines (Tombstone/McAlester
     *  stem `stat`) survive LRU eviction — iOS watches stay resident all session, so their VM
     *  variables never reset mid-run; without this the rebuilt env's stat=0 contradicted the
     *  persisted stopped time base (manualSet() true) until presses re-aligned them. */
    fun persistVars(faceName: String, vars: Map<String, Double>) {
        val store = varStore ?: return
        for ((k, v) in vars) store.put(faceName, k, v)
    }

    /** Load (or fetch cached) on the loader thread; [onLoaded] runs there with null on failure. */
    fun load(face: FaceInfo, onLoaded: ((LoadedFace?) -> Unit)? = null) {
        executor.execute {
            val existing = cached(face.name)
            val loaded = existing ?: try {
                loadFace(face).also { synchronized(this) { cache[face.name] = it } }
            } catch (e: Exception) {
                Log.e("Beryl", "failed to load face ${face.name}", e)
                null
            }
            onLoaded?.invoke(loaded)
        }
    }

    private fun loadFace(face: FaceInfo): LoadedFace {
        val t0 = android.os.SystemClock.uptimeMillis()
        val xml = FaceLoader.text(assets, "facedata/${face.xml}")
        val images = HashMap<String, LoadedImage>()
        for (spec in face.images) {
            images[spec.key] = FaceLoader.image(assets, "facedata/${spec.file}", spec.scale)
        }
        images.putAll(FaceLoader.loadChrome(assets, xml, images.keys))
        // Session-resident states: a reload after LRU eviction reuses the SAME instances, so
        // in-memory-only bits (ringing, a fired target's re-arm marker) survive eviction.
        val st = states(face.name)
        val time = st.time
        val stopwatch = st.stopwatch
        val alarm = st.alarm
        val states = MODES.mapIndexed { i, mode ->
            buildModeState(face, xml, mode, location, varStore, time, stopwatch, alarm).also {
                // Session-lifetime last-drawn angles: a face rebuilt after LRU eviction resumes
                // its hand-sweep state from here (iOS keeps all watches resident — a revisit
                // sweeps only the drift; a first visit this session winds from 12:00).
                it.cache.animStore = animStores.getOrPut("${face.name}/$i") { com.plasticsmoke.beryl.render.AngleAnimStore() }
            }
        }
        Log.d("Beryl", "loaded ${face.name} in ${android.os.SystemClock.uptimeMillis() - t0}ms")
        return LoadedFace(states, images, time, stopwatch, alarm)
    }

    /** Each face keeps its displayed-time offset across relaunches (iOS per-watch defaults). */
    private fun restoreTimeState(faceName: String): WatchTimeState {
        val time = WatchTimeState()
        val saved = varStore?.load(faceName) ?: emptyMap()
        val warp = saved["__timeWarp"]
        if (warp != null) {
            time.restore(warp, saved["__timeWarpBefore"] ?: 1.0, saved["__timeZeroMs"] ?: 0.0)
        }
        time.onChange = {
            varStore?.put(faceName, "__timeWarp", time.warp)
            varStore?.put(faceName, "__timeWarpBefore", time.warpBeforeFreeze)
            varStore?.put(faceName, "__timeZeroMs", time.ourTimeAtZeroMs)
        }
        return time
    }

    /** Each face keeps its chronograph reading/run state across relaunches (iOS defaults). */
    private fun restoreStopwatchState(faceName: String): StopwatchState {
        val sw = StopwatchState()
        val saved = varStore?.load(faceName) ?: emptyMap()
        // zero is anchored to absolute real time, so warp/zero pairs restore verbatim.
        saved["__swWarp"]?.let { sw.stopwatch.restore(it, saved["__swZero"] ?: 0.0) }
        saved["__swLapWarp"]?.let { sw.lap.restore(it, saved["__swLapZero"] ?: 0.0) }
        saved["__swDispWarp"]?.let { sw.display.restore(it, saved["__swDispZero"] ?: 0.0) }
        sw.onChange = {
            varStore?.put(faceName, "__swWarp", sw.stopwatch.warp)
            varStore?.put(faceName, "__swZero", sw.stopwatch.zero)
            varStore?.put(faceName, "__swLapWarp", sw.lap.warp)
            varStore?.put(faceName, "__swLapZero", sw.lap.zero)
            varStore?.put(faceName, "__swDispWarp", sw.display.warp)
            varStore?.put(faceName, "__swDispZero", sw.display.zero)
        }
        return sw
    }

    /** Each face keeps its alarm mode/offset/enabled + countdown state (iOS defaults). */
    private fun restoreAlarmState(faceName: String, time: WatchTimeState): AlarmState {
        val alarm = AlarmState(time)
        val saved = varStore?.load(faceName) ?: emptyMap()
        if ((saved["__alarmEverSet"] ?: 0.0) != 0.0) {
            alarm.restore(
                mode = if ((saved["__alarmMode"] ?: 0.0) != 0.0) AlarmState.Mode.INTERVAL
                else AlarmState.Mode.TARGET,
                specifiedOffset = saved["__alarmSpecOffset"] ?: 0.0,
                enabled = (saved["__alarmEnabled"] ?: 0.0) != 0.0,
                intervalRunning = (saved["__alarmIntRunning"] ?: 0.0) != 0.0,
                intervalTargetMs = (saved["__alarmIntTargetMs"] ?: 0.0).toLong(),
                remainingSec = saved["__alarmIntRemaining"] ?: 0.0,
            )
        }
        alarm.onChange = {
            varStore?.put(faceName, "__alarmEverSet", if (alarm.everSet) 1.0 else 0.0)
            varStore?.put(faceName, "__alarmMode", if (alarm.mode == AlarmState.Mode.INTERVAL) 1.0 else 0.0)
            varStore?.put(faceName, "__alarmSpecOffset", alarm.specifiedOffset)
            varStore?.put(faceName, "__alarmEnabled", if (alarm.enabled) 1.0 else 0.0)
            varStore?.put(faceName, "__alarmIntRunning", if (alarm.intervalRunning) 1.0 else 0.0)
            varStore?.put(faceName, "__alarmIntTargetMs", alarm.intervalTargetMs.toDouble())
            varStore?.put(faceName, "__alarmIntRemaining", alarm.remainingSec)
        }
        return alarm
    }

    companion object {
        val MODES = listOf(ModeFilter.FRONT, ModeFilter.NIGHT, ModeFilter.BACK)
        private const val MAX_LOADED = 3
    }
}
