package com.plasticsmoke.beryl.astro

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Validates the Sun chain (time/Delta-T, Julian centuries, WB sun series, sidereal time) against
 * golden values captured from the chronometer-web TypeScript astronomy — an independent oracle
 * generated by an entirely separate implementation, so this catches real port errors.
 *
 * Golden file: engine/src/test/resources/astro-golden.json (see DEVLOG for how it's produced).
 */
class SunAstroTest {

    private data class Golden(
        val iso: String, val dateInterval: Double,
        val sunRA: Double, val sunDecl: Double, val sunEclLong: Double,
        val gst: Double, val julianCenturies: Double, val deltaT: Double,
        val moonRA: Double, val moonDecl: Double, val moonEclLong: Double,
        val moonAge: Double, val moonPhase: Double,
    )

    /** Minimal JSON-array parser for the flat numeric records in astro-golden.json. */
    private fun loadGolden(): List<Golden> {
        val text = SunAstroTest::class.java.getResourceAsStream("/astro-golden.json")!!
            .bufferedReader().use { it.readText() }
        val records = Regex("""\{(.*?)\}""", RegexOption.DOT_MATCHES_ALL).findAll(text)
        fun field(body: String, key: String): String =
            Regex(""""$key"\s*:\s*("?[^",}]+"?)""").find(body)!!.groupValues[1].trim('"')
        return records.map { m ->
            val b = m.groupValues[1]
            Golden(
                iso = field(b, "iso"),
                dateInterval = field(b, "dateInterval").toDouble(),
                sunRA = field(b, "sunRA").toDouble(),
                sunDecl = field(b, "sunDecl").toDouble(),
                sunEclLong = field(b, "sunEclLong").toDouble(),
                gst = field(b, "gst").toDouble(),
                julianCenturies = field(b, "julianCenturies").toDouble(),
                deltaT = field(b, "deltaT").toDouble(),
                moonRA = field(b, "moonRA").toDouble(),
                moonDecl = field(b, "moonDecl").toDouble(),
                moonEclLong = field(b, "moonEclLong").toDouble(),
                moonAge = field(b, "moonAge").toDouble(),
                moonPhase = field(b, "moonPhase").toDouble(),
            )
        }.toList()
    }

    @Test fun matchesGoldenSunValues() {
        val golden = loadGolden()
        assertEquals(6, golden.size, "expected 6 golden records")
        for (g in golden) {
            val jcr = julianCenturiesSince2000EpochForDateInterval(g.dateInterval)
            assertEquals(g.julianCenturies, jcr.julianCenturiesSince2000Epoch, 1e-10, "julianCenturies @ ${g.iso}")
            assertEquals(g.deltaT, jcr.deltaT, 1e-6, "deltaT @ ${g.iso}")

            val sun = sunRAandDecl(g.dateInterval)
            assertEquals(g.sunRA, sun.rightAscension, 1e-9, "sunRA @ ${g.iso}")
            assertEquals(g.sunDecl, sun.declination, 1e-9, "sunDecl @ ${g.iso}")
            assertEquals(g.sunEclLong, sunEclipticLongitudeForDate(g.dateInterval), 1e-9, "sunEclLong @ ${g.iso}")

            assertEquals(g.gst, convertUTToGSTP03(g.dateInterval), 1e-9, "gst @ ${g.iso}")

            val moon = moonRAAndDecl(g.dateInterval)
            assertEquals(g.moonRA, moon.rightAscension, 1e-9, "moonRA @ ${g.iso}")
            assertEquals(g.moonDecl, moon.declination, 1e-9, "moonDecl @ ${g.iso}")
            assertEquals(g.moonEclLong, moon.moonEclipticLongitude, 1e-9, "moonEclLong @ ${g.iso}")

            val age = moonAge(g.dateInterval)
            assertEquals(g.moonAge, age.age, 1e-9, "moonAge @ ${g.iso}")
            assertEquals(g.moonPhase, age.phase, 1e-9, "moonPhase @ ${g.iso}")
        }
    }
}
